#impportamos imagen base
FROM python:3.12-slim 

#crear capeta de trabajo
WORKDIR /app

#copiamos el archivo de requerimientos
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#copiar el proyecto
COPY ./app ./app

#exponer el puerto
EXPOSE 5000

#comando para ejecutar fastAPI
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000" , "--reload"]